### ISSUE TITLE
[enhancement] R2730DB/RC10D1

### ISSUE THREAD

**Issue by Moonstone3010** [norbert78x/Edifier-RC10E#1]
Hi Norbert,
first of all thanks a lot, the application is great. You're a lifesaver, because my remote control just died and I can't find this particular version anywhere.

I have R2730DB speakers with RC10D1 remote control - it has 9 buttons, looks like RC10E without the last 3 buttons. However, the codes for on/off and mute are swapped places. If you could still find the nerve to make another version it would be great.

**Comment by norbicki** [comment]
Removing three buttons and replacing two is a simple matter. Can you confirm that all buttons except on/off and mute work correctly on R2730DB speakers? I don't have such speakers to check.

**Comment by norbicki** [comment]
Thread moved to [Edifier-RC10D1](https://github.com/norbicki/Edifier-RC10D1/issues/1)
